# CI/CD configuration file for the 'natp' service (The Router)
# FIX: Image name must be lowercase 'natp'

# --- Custom substitution variable definition ---
substitutions:
  _TAG_VERSION: ${COMMIT_SHA}
# -----------------------------------------------

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/natp:${_TAG_VERSION}'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/natp:${_TAG_VERSION}'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'natp' # Service Name (Lowercase mandatory)
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/natp:${_TAG_VERSION}'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      # ADDED: VPC Connector for Redis access
      - '--vpc-connector=amorce-vpc-connector'
      # Injection of vital environment variables for Prod
      # REDIS_HOST updated to: 10.185.13.251
      - '--set-env-vars=TRUST_DIRECTORY_URL=https://amorce-trust-api-425870997313.us-central1.run.app,AGENT_API_KEY=sk-atp-amorce-dev-2024,AGENT_ID=e4b0c7c8-4b9f-4b0d-8c1a-2b9d1c9a0c1a,GCP_PROJECT_ID=amorce-prod-rgosselin,SECRET_NAME=atp-agent-private-key,REDIS_HOST=10.185.13.251'
      # NOTE: You will need to add GOOGLE_API_KEY manually in the Cloud Run console for security,
      # or add it here if you accept it in the source code (discouraged but quick).

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/natp:${_TAG_VERSION}'

options:
  logging: CLOUD_LOGGING_ONLY